# Generated by Django 4.1.1 on 2022-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_state', models.CharField(max_length=100, null=True)),
                ('station_city', models.CharField(max_length=100, null=True)),
                ('station_name', models.CharField(max_length=100, null=True)),
                ('station_locality', models.CharField(max_length=100, null=True)),
                ('station_areacode', models.CharField(max_length=10, null=True)),
                ('station_contact', models.CharField(max_length=12, null=True)),
            ],
            options={
                'db_table': 'police_station_details',
            },
        ),
    ]
