# Generated by Django 4.1.1 on 2022-10-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceOfficerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_station', models.CharField(max_length=100, null=True)),
                ('officer_badgeno', models.CharField(max_length=100, null=True)),
                ('officer_name', models.CharField(max_length=100, null=True)),
                ('officer_email', models.EmailField(max_length=100, null=True)),
                ('officer_number', models.CharField(max_length=100, null=True)),
                ('officer_password', models.CharField(max_length=100, null=True)),
                ('officer_profile', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'police_officers_details',
            },
        ),
    ]
