# Generated by Django 4.1.1 on 2022-10-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_policeofficermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_aadhar', models.CharField(max_length=100, null=True)),
                ('crime_type', models.CharField(max_length=100, null=True)),
                ('crime_desc', models.CharField(max_length=100, null=True)),
                ('crime_added_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'crime_details',
            },
        ),
    ]
