# Generated by Django 4.1.1 on 2022-10-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_crimemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_aadhar', models.CharField(max_length=100, null=True)),
                ('criminal_name', models.CharField(max_length=100, null=True)),
                ('criminal_email', models.EmailField(max_length=100, null=True)),
                ('criminal_contact', models.CharField(max_length=100, null=True)),
                ('criminal_city', models.CharField(max_length=100, null=True)),
                ('criminal_profile', models.ImageField(null=True, upload_to='images/')),
                ('criminal_crime_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'criminals_details',
            },
        ),
    ]
