# Generated by Django 4.1 on 2022-12-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_criminalmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalmodel',
            name='aadhar_block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminalmodel',
            name='city_block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminalmodel',
            name='contact_block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminalmodel',
            name='date_block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminalmodel',
            name='email_block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminalmodel',
            name='name_block',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criminalmodel',
            name='profile_block',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
