# Generated by Django 4.1 on 2022-12-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_criminalmodel_aadhar_block_criminalmodel_city_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalmodel',
            name='criminal_crime_date',
            field=models.DateField(null=True),
        ),
    ]
