# Generated by Django 4.1 on 2022-12-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_criminalmodel_criminal_crime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimemodel',
            name='aadhar_blk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crimemodel',
            name='date_blk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crimemodel',
            name='desc_blk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crimemodel',
            name='type_blk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crimemodel',
            name='crime_added_date',
            field=models.DateField(null=True),
        ),
    ]
